# Generated by Django 4.2.4 on 2024-09-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trvels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('difficulty', models.CharField(max_length=255)),
                ('age_group', models.CharField(max_length=255)),
                ('altitude', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('includes', models.JSONField()),
                ('about', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
