# Generated by Django 4.2.4 on 2024-09-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trvels', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='Cname',
            field=models.CharField(default='India', max_length=255),
        ),
    ]
