# Generated by Django 4.2.4 on 2024-09-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trvels', '0003_location_cname'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='brochures/'),
        ),
    ]
