# Generated by Django 4.2.4 on 2024-09-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trvels', '0004_location_brochure'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='line',
            field=models.TextField(null=True),
        ),
    ]
