# Generated by Django 4.2.4 on 2024-09-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trvels', '0005_location_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
                ('place', models.CharField(max_length=100)),
                ('number_of_persons', models.IntegerField()),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('transportation_method', models.CharField(choices=[('Flight', 'Flight'), ('Train', 'Train')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
