# Generated by Django 4.2.4 on 2024-09-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trvels', '0007_contact_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='backimage',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
